<?php
// Post Meta Fields Template - Generated by Teznevisan Theme
if (!defined("ABSPATH")) exit;
?>
<div class="teznevisan-meta-tabs">
    <nav class="meta-nav-tabs">
        <a href="#basic-settings" class="nav-tab nav-tab-active">تنظیمات پایه</a>
        <a href="#content-settings" class="nav-tab">محتوای اضافی</a>
        <a href="#related-settings" class="nav-tab">مطالب مرتبط</a>
    </nav>
    
    <div id="basic-settings" class="meta-tab-content active">
        <table class="form-table">
            <tr>
                <th><label for="post_subtitle">زیرعنوان مطلب</label></th>
                <td>
                    <input type="text" id="post_subtitle" name="post_subtitle" value="<?php echo esc_attr($subtitle); ?>" class="large-text">
                    <p class="description">زیرعنوان توضیحی برای مطلب</p>
                </td>
            </tr>
        </table>
    </div>
    
    <div id="content-settings" class="meta-tab-content">
        <table class="form-table">
            <tr>
                <th><label>نکات کلیدی</label></th>
                <td>
                    <div id="takeaways-container">
                        <?php foreach ($key_takeaways as $index => $takeaway) : ?>
                            <div class="takeaway-item">
                                <input type="text" name="key_takeaways[]" value="<?php echo esc_attr($takeaway); ?>" class="large-text" placeholder="نکته کلیدی">
                                <button type="button" class="button remove-takeaway">حذف</button>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <button type="button" id="add-takeaway" class="button button-primary">افزودن نکته</button>
                </td>
            </tr>
        </table>
    </div>
    
    <div id="related-settings" class="meta-tab-content">
        <table class="form-table">
            <tr>
                <th><label for="related_service_id">خدمت مرتبط</label></th>
                <td>
                    <select id="related_service_id" name="related_service_id">
                        <option value="">انتخاب خدمت مرتبط</option>
                        <?php
                        $services = get_posts(array("post_type" => "services", "posts_per_page" => -1));
                        foreach ($services as $service) {
                            echo "<option value=\"" . $service->ID . "\"" . selected($related_service_id, $service->ID, false) . ">";
                            echo esc_html($service->post_title);
                            echo "</option>";
                        }
                        ?>
                    </select>
                </td>
            </tr>
        </table>
    </div>
</div>

<script>
jQuery(document).ready(function($) {
    $(".meta-nav-tabs a").click(function(e) {
        e.preventDefault();
        $(".nav-tab").removeClass("nav-tab-active");
        $(".meta-tab-content").removeClass("active");
        $(this).addClass("nav-tab-active");
        $($(this).attr("href")).addClass("active");
    });
    
    $("#add-takeaway").click(function() {
        var html = "<div class=\"takeaway-item\">" +
            "<input type=\"text\" name=\"key_takeaways[]\" class=\"large-text\" placeholder=\"نکته کلیدی\">" +
            "<button type=\"button\" class=\"button remove-takeaway\">حذف</button>" +
            "</div>";
        $("#takeaways-container").append(html);
    });
    
    $(document).on("click", ".remove-takeaway", function() {
        $(this).closest(".takeaway-item").remove();
    });
});
</script>